events {}

http {
    upstream counter_backend {
        server counter-app:3000;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://counter_backend;
        }
    }
}